- platform: template
  sensors:
    is_crow_detected:
      friendly_name: Is Crow Detected
      value_template: >-
        {{ not is_state_attr('image_processing.doods_crowscamera', 'total_matches', 0 ) }}
    is_crow_detection_running:
      friendly_name: Is Crow Detection Running
      value_template: >-
        {{ is_state('input_boolean.crow_motion_scanning', 'on') }}